// Mapa estático UUID(concepto CIEL país) -> ISO 3166-1 alpha-2.
// Generado desde el set CIEL 165657 (short name alpha-3 -> alpha-2). 165 países.
// Overrides: England/UK->GB, Kosovo->XK (de facto), Palestine->PS.
export const COUNTRY_UUID_TO_ISO2 = {
  "165705AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AF", // Afganistán
  "165674AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AL", // Albania
  "165659AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "DE", // Alemania
  "165757AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "DZ", // Algeria
  "165691AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AD", // Andorra
  "165798AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AG", // Antigua y Barbuda
  "165722AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SA", // Arabia Saudita
  "165821AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AR", // Argentina
  "165675AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AM", // Armenia
  "165742AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AU", // Australia
  "165666AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AT", // Austria
  "165676AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AZ", // Azerbaiján
  "165713AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BH", // Bahrain
  "165706AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BD", // Bangladesh
  "165800AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BB", // Barbados
  "165811AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BZ", // Belice
  "165677AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BY", // Bielorrusia
  "165678AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BA", // Bosnia-Herzegovina
  "165766AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BW", // Botswana
  "165823AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BR", // Brasil
  "165731AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BN", // Brunéi
  "165679AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BG", // Bulgaria
  "165744AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BI", // Burundí
  "165707AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BT", // Bután
  "165660AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BE", // Bélgica
  "165733AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KH", // Camboya
  "165745AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CM", // Camerún
  "165818AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CA", // Canadá
  "165747AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TD", // Chad
  "165824AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CL", // Chile
  "165634AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CN", // China
  "165680AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CY", // Chipre
  "165825AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CO", // Colombia
  "165783AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CI", // Costa Marfil
  "165812AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CR", // Costa Rica
  "165667AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "HR", // Croacia
  "165802AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CU", // Cuba
  "165661AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "DK", // Dinamarca
  "165801AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "DM", // Dominica
  "165826AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "EC", // Ecuador
  "165758AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "EG", // Egipto
  "165813AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SV", // El Salvador
  "165724AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "AE", // Emiratos Arabes Unidos
  "165671AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SK", // Eslovaquia
  "165672AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SI", // Eslovenia
  "165699AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "ES", // España
  "165822AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BO", // Estado Plurinacional de Bolivia
  "165820AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "US", // Estados Unidos de América
  "165681AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "EE", // Estonia
  "165641AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "ET", // Etiopía
  "165687AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "RU", // Federación Rusa - Europa
  "165663AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "FI", // Finlandia
  "165658AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "FR", // Francia
  "165750AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GA", // Gabón
  "165790AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GM", // Gambia
  "165682AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GE", // Georgia
  "165780AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GH", // Ghana
  "165803AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GD", // Granada
  "165683AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GR", // Grecia
  "165814AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GT", // Guatemala
  "165782AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GW", // Guinea Bissau
  "165827AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GY", // Guyana
  "165804AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "HT", // Haití
  "165815AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "HN", // Honduras
  "165704AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "HK", // Hong Kong
  "165669AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "HU", // Hungría
  "165708AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "IN", // India
  "165735AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "ID", // Indonesia
  "165662AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GB", // Inglaterra
  "165714AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "IQ", // Irak
  "165665AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "IS", // Islandia
  "165755AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KM", // Islas Comoras
  "165922AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GB", // Islas del Reino Unido de Gran Bretaña e Irlanda del Norte
  "165715AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "IL", // Israel
  "165805AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "JM", // Jamaica
  "165637AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "JP", // Japón
  "165716AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "JO", // Jordania
  "165725AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KZ", // Kazakistán
  "162883AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KE", // Kenia
  "165726AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KG", // Kirguizistán
  "165717AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KW", // Kuwait
  "165799AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "BS", // Las Bahamas
  "165684AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LV", // Letonia
  "162606AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LR", // Liberia
  "165759AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LY", // Libia
  "165690AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LI", // Liechtenstein
  "165685AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LT", // Lituania
  "165693AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LU", // Luxemburgo
  "165718AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LB", // Líbano
  "165737AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MY", // Malasia
  "165709AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MV", // Maldivas
  "165692AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MT", // Malta
  "165785AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "ML", // Malí
  "165786AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MR", // Mauritania
  "165727AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MN", // Mongolia
  "165773AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MZ", // Mozambique
  "165732AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MM", // Myanmar
  "165819AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MX", // Méjico
  "165694AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MC", // Mónaco
  "165710AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "NP", // Nepal
  "165816AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "NI", // Nicaragua
  "162609AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "NG", // Nigeria
  "165696AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "NO", // Noruega
  "165743AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "NZ", // Nueva Zelanda
  "165751AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "NE", // Níger
  "165719AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "OM", // Omán
  "167024AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "PS", // Palestine
  "165817AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "PA", // Panamá
  "165711AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "PK", // Paquistán
  "165828AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "PY", // Paraguay
  "165695AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "NL", // Países Bajos
  "165829AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "PE", // Perú
  "165670AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "PL", // Polonia
  "165697AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "PT", // Portugal
  "165806AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "PR", // Puerto Rico
  "165721AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "QA", // Quatar
  "165749AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CG", // Republic of Congo
  "166062AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "XK", // Republic of Kosovo
  "165746AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CF", // República Africana Central
  "165720AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "YE", // República Arabe de Yemén
  "165832AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "VE", // República Bolivariana de Venezuela
  "165668AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CZ", // República Checa
  "165736AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LA", // República Democrática Popular Lao
  "165703AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KP", // República Democrática Popular de Corea
  "165734AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TL", // República Democrática de Timor Oriental
  "165748AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CD", // República Democrática del Congo
  "165639AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TZ", // República Unida de Tanzania
  "165638AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KR", // República de Corea
  "165781AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "GN", // República de Guinea
  "165698AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "IE", // República de Irlanda
  "165664AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "MK", // República de Macedonia
  "9175e03d-8e2c-4171-950f-3fd742b24926": "MD", // República de Moldavia
  "166072AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "RS", // República de Serbia
  "165752AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "RW", // Ruanda
  "165686AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "RO", // Rumania
  "165807AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "KN", // San Cristóbal y Nevis
  "165701AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SM", // San Marino
  "165809AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "VC", // San Vicente y Granadinas
  "165808AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LC", // Santa Lucía
  "165787AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "ST", // Santo Tomé y Príncipe
  "162610AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SN", // Senegal
  "165756AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SC", // Seychelles
  "162608AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SL", // Sierra Leona
  "165739AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SG", // Singapur
  "165723AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SY", // Siria
  "165753AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SO", // Somalía
  "165765AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SS", // South Sudan
  "165712AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "LK", // Sri Lanka
  "165770AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "ZA", // Sudáfrica
  "165764AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SD", // Sudán
  "165700AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SE", // Suecia
  "165673AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "CH", // Suiza
  "165830AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "SR", // Suriname
  "165728AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TJ", // Tadjikistán
  "165740AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TH", // Tailandia
  "165702AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TW", // Taiwán
  "165810AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TT", // Trinidad y Tobago
  "165729AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TM", // Turkemenistán
  "165688AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "TR", // Turquía - país
  "165689AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "UA", // Ucrania
  "162884AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "UG", // Uganda
  "165831AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "UY", // Uruguay
  "165730AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "UZ", // Uzbequistán
  "165741AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "VN", // Viet Nam
  "165754AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA": "ZM", // Zambia
};
